// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ClarityDisconnectedSolid: typeof import('~icons/clarity/disconnected-solid')['default']
    CryptocurrencyColorXpa: typeof import('./components/CustomIcons/CryptocurrencyColorXpa.vue')['default']
    EmojioneV1Fire: typeof import('~icons/emojione-v1/fire')['default']
    EmojioneV1RingingBell: typeof import('~icons/emojione-v1/ringing-bell')['default']
    FileBoard: typeof import('./components/FileBoard/FileBoard.vue')['default']
    JamArrowSquareRight: typeof import('~icons/jam/arrow-square-right')['default']
    JamMessageWritingF: typeof import('~icons/jam/message-writing-f')['default']
    MaterialSymbolsAutoDeleteOutline: typeof import('./components/CustomIcons/MaterialSymbolsAutoDeleteOutline.vue')['default']
    MaterialSymbolsContentCopyOutlineSharp: typeof import('./components/CustomIcons/MaterialSymbolsContentCopyOutlineSharp.vue')['default']
    MaterialSymbolsKeyboardDoubleArrowDown: typeof import('~icons/material-symbols/keyboard-double-arrow-down')['default']
    MdiFolderArrowUpDownOutline: typeof import('~icons/mdi/folder-arrow-up-down-outline')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillIconsViteDark: typeof import('./components/CustomIcons/SkillIconsViteDark.vue')['default']
    SkillIconsViteLight: typeof import('./components/CustomIcons/SkillIconsViteLight.vue')['default']
    SvgSpinners3DotsBounce: typeof import('./components/CustomIcons/SvgSpinners3DotsBounce.vue')['default']
    SvgSpinnersBlocksShuffle3: typeof import('./components/CustomIcons/SvgSpinnersBlocksShuffle3.vue')['default']
    TransferDesc: typeof import('./components/FileBoard/TransferDesc.vue')['default']
  }
}
